// STYLING
import "./globals.css";
// COMPONENTS
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import ThemeToggle from "@/components/header/themeToggle";

// META - TITLE AND DESCRIPTION
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-fsbody">
        <ThemeToggle/>
        <div className="flex flex-col min-h-screen">
          <Header/>
          <div className="mainContent grow">{children}</div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
